#!/usr/bin/env python3
"""
AI Report Analyzer using Google Gemini

Analyzes reports using Google Gemini API.

Usage:
    # Option 1: Use prompt file (generated by generate_analysis_prompt.py)
    python -m impactlens.scripts.analyze_with_gemini \
      --prompt-file reports/prompts/analysis_prompt_combined_pr_report_*.txt \
      --output-dir reports/prompts

    # Option 2: Use Gemini CLI via npx (requires Node.js)
    python -m impactlens.scripts.analyze_with_gemini \
      --prompt-file reports/prompts/analysis_prompt_combined_pr_report_*.txt \
      --output-dir reports/prompts \
      --use-cli

    # Option 3: Direct API call with custom prompt
    export GEMINI_API_KEY="your-api-key"
    python -m impactlens.scripts.analyze_with_gemini \
      --prompt-file custom_prompt.txt \
      --output-dir output
"""

import os
import sys
import argparse
import subprocess
import json
from pathlib import Path
from datetime import datetime
from glob import glob

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from impactlens.utils.logger import logger
from impactlens.utils.workflow_utils import upload_to_google_sheets


def find_latest_file(file_pattern: str) -> str:
    """Find the most recent file matching the pattern."""
    matches = glob(file_pattern)

    if not matches:
        logger.error(f"❌ No files found matching: {file_pattern}")
        logger.error("")
        logger.error("💡 Troubleshooting:")
        logger.error("   1. Check if the file exists in the specified directory")
        logger.error("   2. Verify the file path is correct")
        logger.error("   3. If using wildcards (*), ensure at least one matching file exists")
        logger.error("")
        sys.exit(1)

    # Sort by modification time (most recent first)
    matches.sort(key=os.path.getmtime, reverse=True)
    return matches[0]


def read_prompt(prompt_path: str) -> str:
    """Read the analysis prompt from file."""
    with open(prompt_path, "r", encoding="utf-8") as f:
        return f.read()


def call_gemini_api(prompt: str, api_key: str = None) -> str:
    """
    Call Google Gemini API to analyze the prompt.

    Args:
        prompt: The analysis prompt to send to Gemini
        api_key: Gemini API key (if None, reads from GOOGLE_API_KEY env var)

    Returns:
        Analysis text from Gemini API

    Raises:
        RuntimeError: If API call fails
        ValueError: If API key not provided
    """
    logger.info("🤖 Calling Google Gemini API for analysis...")

    try:
        from google import genai
    except ImportError:
        raise ImportError(
            "google-genai library not installed. Install with:\n" "  pip install google-genai"
        )

    # Get API key (try GOOGLE_API_KEY first, then GEMINI_API_KEY for backward compatibility)
    if not api_key:
        api_key = os.environ.get("GOOGLE_API_KEY") or os.environ.get("GEMINI_API_KEY")

    if not api_key:
        raise ValueError(
            "Gemini API key not found. Either:\n"
            "  1. Set GOOGLE_API_KEY environment variable, or\n"
            "  2. Pass --gemini-api-key parameter"
        )

    try:
        # Initialize client
        client = genai.Client(api_key=api_key)

        # Get available models and select the best Gemini model
        logger.info("   Selecting best available Gemini model...")
        try:
            models = client.models.list()
            candidate_models = [
                m
                for m in models
                if "gemini" in m.name.lower()
                and ("pro" in m.name.lower() or "flash" in m.name.lower())
            ]

            if candidate_models:
                model_name = sorted(candidate_models, key=lambda m: m.name)[-1].name
            else:
                model_name = "gemini-2.0-flash-exp"
        except Exception:
            # Fallback to default model if listing fails
            model_name = "gemini-2.0-flash-exp"

        logger.info(f"   Using model: {model_name}")

        # Generate content
        logger.info("   Sending request to Gemini...")
        response = client.models.generate_content(
            model=model_name,
            contents=prompt,
        )

        if not response.text:
            raise RuntimeError("Gemini API returned empty response")

        analysis = response.text.strip()

        logger.info("   ✓ Analysis completed successfully")
        logger.info(f"   Model: {model_name}")
        logger.info(f"   Response length: {len(analysis)} characters")

        return analysis

    except Exception as e:
        raise RuntimeError(f"Gemini API call failed: {e}")


def save_analysis(
    analysis_text: str,
    report_path: str,
    output_dir: str = "reports/prompts",
    analysis_tool: str = "Google Gemini",
    prompt_path: str = None,
) -> str:
    """Save analysis to file."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    # Determine report type for filename based on prompt file or report path
    if "combined" in report_path.lower():
        # Combined analysis (JIRA + PR together)
        prefix = "gemini_analysis_combined"
        report_type = "JIRA + PR Combined"
    elif "github" in report_path.lower() or "pr" in report_path.lower():
        prefix = "gemini_analysis_pr"
        report_type = "GITHUB PR"
    else:
        prefix = "gemini_analysis_jira"
        report_type = "JIRA"

    output_filename = f"{prefix}_{timestamp}.txt"
    output_path = Path(output_dir) / output_filename
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Extract source reports from prompt file if available
    source_reports = []
    if prompt_path and Path(prompt_path).exists():
        try:
            with open(prompt_path, "r", encoding="utf-8") as f:
                prompt_content = f.read()
                # Look for "Source Reports:" section
                if "Source Reports:" in prompt_content:
                    lines = prompt_content.split("\n")
                    in_source_section = False
                    for line in lines:
                        if "Source Reports:" in line:
                            in_source_section = True
                            continue
                        if in_source_section:
                            if line.strip().startswith("- "):
                                source_reports.append(line.strip()[2:])  # Remove "- " prefix
                            elif line.strip().startswith("=") or not line.strip().startswith("-"):
                                break
        except Exception:
            pass  # If extraction fails, continue without source reports

    # Format the final report
    report_lines = []
    report_lines.append("=" * 80)
    report_lines.append("AI-POWERED METRICS ANALYSIS REPORT")
    report_lines.append("=" * 80)
    report_lines.append("")
    report_lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    report_lines.append(f"Report Type: {report_type}")
    report_lines.append(f"Analysis Tool: {analysis_tool}")
    report_lines.append(f"Source Prompt: {Path(report_path).name if report_path else 'N/A'}")

    if source_reports:
        report_lines.append("")
        report_lines.append("Source Data Reports:")
        for report in source_reports:
            report_lines.append(f"  {report}")

    report_lines.append("")
    report_lines.append("=" * 80)
    report_lines.append("")
    report_lines.append(analysis_text)
    report_lines.append("")
    report_lines.append("=" * 80)
    report_lines.append(f"Report saved: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    report_lines.append("=" * 80)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(report_lines))

    return str(output_path)


def main():
    parser = argparse.ArgumentParser(
        description="Analyze reports using Google Gemini",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic usage with API key from environment
  export GOOGLE_API_KEY="your-api-key"
  python -m impactlens.scripts.analyze_with_gemini \\
    --prompt-file "reports/prompts/analysis_prompt_*.txt"

  # With explicit API key
  python -m impactlens.scripts.analyze_with_gemini \\
    --prompt-file "reports/prompts/combined_analysis_prompt_*.txt" \\
    --gemini-api-key "your-api-key" \\
    --output-dir "reports/prompts"

  # Specify report path for better metadata
  python -m impactlens.scripts.analyze_with_gemini \\
    --prompt-file "reports/prompts/combined_analysis_prompt_*.txt" \\
    --report-path "reports/team/jira/combined_jira_report_*.tsv" \\
    --output-dir "reports/prompts"
        """,
    )

    parser.add_argument(
        "--prompt-file",
        required=False,
        help="Path to the prompt file (supports wildcards). If not specified, searches reports/prompts/",
    )
    parser.add_argument(
        "--report-path",
        default="",
        help="Path to the original report file (for metadata, optional)",
    )
    parser.add_argument(
        "--output-dir",
        default="reports/prompts",
        help="Output directory for analysis results (default: reports/prompts)",
    )
    parser.add_argument(
        "--gemini-api-key",
        help="Gemini API key (default: from GEMINI_API_KEY env var)",
    )
    parser.add_argument(
        "--no-upload",
        action="store_true",
        help="Skip uploading to Google Sheets",
    )
    parser.add_argument(
        "--config",
        help="Path to config file/directory (used to extract sheet prefix)",
    )

    args = parser.parse_args()

    logger.info("=" * 80)
    logger.info("AI Report Analyzer (Google Gemini Edition)")
    logger.info("=" * 80)
    logger.info("")

    # Find prompt file
    if args.prompt_file:
        # Use specified prompt file
        prompt_path = find_latest_file(args.prompt_file)
    else:
        # Auto-search in output directory
        prompt_pattern = f"{args.output_dir}/*analysis_prompt*.txt"
        prompt_files = glob(prompt_pattern)

        # Filter out Gemini result files
        prompt_files = [f for f in prompt_files if not Path(f).name.startswith("gemini_analysis_")]

        if not prompt_files:
            logger.error(f"❌ No prompt files found in: {args.output_dir}/")
            logger.error("   Expected: *analysis_prompt*.txt or combined_analysis_prompt_*.txt")
            logger.error("   Run: impactlens full --config <config> to generate prompts first")
            sys.exit(1)

        # Use most recent prompt
        prompt_path = max(prompt_files, key=os.path.getmtime)
        logger.info(f"🔍 Auto-detected prompt: {Path(prompt_path).name}")

    logger.info(f"📄 Prompt file: {Path(prompt_path).name}")
    logger.info(f"   Mode: Gemini API")
    logger.info("")

    try:
        # Call Gemini API
        prompt = read_prompt(prompt_path)
        analysis = call_gemini_api(prompt, api_key=args.gemini_api_key)

        logger.info("")
        logger.info("=" * 80)
        logger.info("📊 ANALYSIS RESULT")
        logger.info("=" * 80)
        logger.info("")
        print(analysis)
        logger.info("")

        # Save analysis
        logger.info("💾 Saving analysis to file...")
        # Use prompt_path to determine type (combined/jira/pr) since report_path may be empty
        source_path = args.report_path if args.report_path else prompt_path
        output_file = save_analysis(
            analysis, source_path, args.output_dir, "Google Gemini API", prompt_path=prompt_path
        )
        logger.info(f"   ✓ Saved to: {output_file}")
        logger.info("")

        # Auto-upload to Google Sheets (unless --no-upload specified)
        config_path = Path(args.config) if args.config else None
        upload_to_google_sheets(
            Path(output_file), skip_upload=args.no_upload, config_path=config_path
        )

        # Summary
        logger.info("=" * 80)
        logger.info("✅ ANALYSIS COMPLETE!")
        logger.info("=" * 80)
        logger.info("")
        logger.info(f"📄 Prompt: {Path(prompt_path).name}")
        logger.info(f"💾 Output: {output_file}")
        logger.info("")
        logger.info("=" * 80)

        return 0

    except Exception as e:
        logger.error("")
        logger.error("=" * 80)
        logger.error("❌ ANALYSIS FAILED")
        logger.error("=" * 80)
        logger.error("")
        logger.error(f"Error: {str(e)}")
        logger.error("")
        return 1


if __name__ == "__main__":
    sys.exit(main())
