#!/usr/bin/env python3
"""
AI Report Analyzer using Google Gemini

Analyzes reports using Google Gemini API.

Usage:
    # Option 1: Use prompt file (generated by analyze_with_claude_code.py)
    python -m impactlens.scripts.analyze_with_gemini \
      --prompt-file reports/prompts/analysis_prompt_combined_pr_report_*.txt \
      --output-dir reports/prompts

    # Option 2: Use Gemini CLI via npx (requires Node.js)
    python -m impactlens.scripts.analyze_with_gemini \
      --prompt-file reports/prompts/analysis_prompt_combined_pr_report_*.txt \
      --output-dir reports/prompts \
      --use-cli

    # Option 3: Direct API call with custom prompt
    export GEMINI_API_KEY="your-api-key"
    python -m impactlens.scripts.analyze_with_gemini \
      --prompt-file custom_prompt.txt \
      --output-dir output
"""

import os
import sys
import argparse
import subprocess
import json
from pathlib import Path
from datetime import datetime
from glob import glob

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from impactlens.utils.logger import logger
from impactlens.utils.workflow_utils import upload_to_google_sheets


def find_latest_file(file_pattern: str) -> str:
    """Find the most recent file matching the pattern."""
    matches = glob(file_pattern)

    if not matches:
        logger.error(f"❌ No files found matching: {file_pattern}")
        logger.error("")
        logger.error("💡 Troubleshooting:")
        logger.error("   1. Check if the file exists in the specified directory")
        logger.error("   2. Verify the file path is correct")
        logger.error("   3. If using wildcards (*), ensure at least one matching file exists")
        logger.error("")
        sys.exit(1)

    # Sort by modification time (most recent first)
    matches.sort(key=os.path.getmtime, reverse=True)
    return matches[0]


def read_prompt(prompt_path: str) -> str:
    """Read the analysis prompt from file."""
    with open(prompt_path, "r", encoding="utf-8") as f:
        return f.read()


def call_gemini_api(prompt: str, api_key: str = None, timeout: int = 300) -> str:
    """
    Call Google Gemini API to analyze the prompt.

    Args:
        prompt: The analysis prompt to send to Gemini
        api_key: Gemini API key (if None, reads from GEMINI_API_KEY env var)
        timeout: Timeout in seconds (default: 300 = 5 minutes)

    Returns:
        Analysis text from Gemini API

    Raises:
        RuntimeError: If API call fails
        ValueError: If API key not provided
    """
    logger.info("🤖 Calling Google Gemini API for analysis...")
    logger.info(f"   Timeout: {timeout}s")

    try:
        import google.generativeai as genai
    except ImportError:
        raise ImportError(
            "google-generativeai library not installed. Install with:\n"
            "  pip install google-generativeai>=0.8.0"
        )

    # Get API key
    if not api_key:
        api_key = os.environ.get("GEMINI_API_KEY")

    if not api_key:
        raise ValueError(
            "Gemini API key not found. Either:\n"
            "  1. Set GEMINI_API_KEY environment variable, or\n"
            "  2. Pass --gemini-api-key parameter"
        )

    try:
        # Configure Gemini
        genai.configure(api_key=api_key)

        # Use Gemini Pro model
        model = genai.GenerativeModel("gemini-2.0-flash-exp")

        # Generate content
        logger.info("   Sending request to Gemini...")
        response = model.generate_content(
            prompt,
            request_options={"timeout": timeout},
        )

        if not response.text:
            raise RuntimeError("Gemini API returned empty response")

        analysis = response.text.strip()

        logger.info("   ✓ Analysis completed successfully")
        logger.info(f"   Model: gemini-2.0-flash-exp")
        logger.info(f"   Response length: {len(analysis)} characters")

        return analysis

    except Exception as e:
        raise RuntimeError(f"Gemini API call failed: {e}")


def call_gemini_cli(prompt_file: str, timeout: int = 300) -> str:
    """
    Call Gemini CLI via npx to analyze the prompt.

    Args:
        prompt_file: Path to the prompt file
        timeout: Timeout in seconds (default: 300 = 5 minutes)

    Returns:
        Analysis text from Gemini CLI

    Raises:
        RuntimeError: If CLI call fails
        FileNotFoundError: If npx not found
    """
    logger.info("🤖 Calling Gemini CLI (via npx) for analysis...")
    logger.info(f"   Prompt file: {prompt_file}")
    logger.info(f"   Timeout: {timeout}s")

    # Check if GEMINI_API_KEY is set
    if not os.environ.get("GEMINI_API_KEY"):
        raise ValueError(
            "GEMINI_API_KEY environment variable not set.\n"
            "Please set it before using Gemini CLI:\n"
            "  export GEMINI_API_KEY='your-api-key'"
        )

    try:
        # Read the prompt
        with open(prompt_file, "r", encoding="utf-8") as f:
            prompt = f.read()

        # Call Gemini CLI with auto-accept (-y) and text output (-o text)
        result = subprocess.run(
            ["npx", "@google/gemini-cli", prompt, "-y", "-o", "text"],
            capture_output=True,
            text=True,
            timeout=timeout,
            check=True,
        )

        analysis = result.stdout.strip()

        if not analysis:
            raise RuntimeError("Gemini CLI returned empty response")

        logger.info("   ✓ Analysis completed successfully")
        return analysis

    except FileNotFoundError:
        raise FileNotFoundError(
            "npx not found. Please install Node.js first:\n"
            "  https://nodejs.org/\n"
            "  OR use --use-api flag to call Gemini API directly"
        )
    except subprocess.TimeoutExpired:
        raise RuntimeError(f"Gemini CLI timed out after {timeout}s")
    except subprocess.CalledProcessError as e:
        error_msg = e.stderr if e.stderr else "Unknown error"
        raise RuntimeError(f"Gemini CLI failed: {error_msg}")


def save_analysis(
    analysis_text: str,
    report_path: str,
    output_dir: str = "reports/prompts",
    analysis_tool: str = "Google Gemini",
) -> str:
    """Save analysis to file."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    # Determine report type for filename
    if "github" in report_path.lower() or "pr" in report_path.lower():
        prefix = "gemini_analysis_pr"
        report_type = "GITHUB PR"
    else:
        prefix = "gemini_analysis_jira"
        report_type = "JIRA"

    output_filename = f"{prefix}_{timestamp}.txt"
    output_path = Path(output_dir) / output_filename
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Format the final report
    report_lines = []
    report_lines.append("=" * 80)
    report_lines.append("AI-POWERED METRICS ANALYSIS REPORT")
    report_lines.append("=" * 80)
    report_lines.append("")
    report_lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    report_lines.append(f"Report Type: {report_type}")
    report_lines.append(f"Analysis Tool: {analysis_tool}")
    report_lines.append(f"Source Report: {Path(report_path).name if report_path else 'N/A'}")
    report_lines.append("")
    report_lines.append("=" * 80)
    report_lines.append("")
    report_lines.append(analysis_text)
    report_lines.append("")
    report_lines.append("=" * 80)
    report_lines.append(f"Report saved: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    report_lines.append("=" * 80)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(report_lines))

    return str(output_path)


def main():
    parser = argparse.ArgumentParser(
        description="Analyze reports using Google Gemini",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Use Gemini API (default)
  export GEMINI_API_KEY="your-api-key"
  python -m impactlens.scripts.analyze_with_gemini \\
    --prompt-file "reports/prompts/analysis_prompt_*.txt" \\
    --output-dir "reports/prompts"

  # Use Gemini CLI via npx
  export GEMINI_API_KEY="your-api-key"
  python -m impactlens.scripts.analyze_with_gemini \\
    --prompt-file "reports/prompts/analysis_prompt_*.txt" \\
    --output-dir "reports/prompts" \\
    --use-cli

  # Specify report path for better metadata
  python -m impactlens.scripts.analyze_with_gemini \\
    --prompt-file "reports/prompts/analysis_prompt_combined_pr_report.txt" \\
    --report-path "reports/github/combined_pr_report_20250119.tsv" \\
    --output-dir "reports/prompts"
        """,
    )

    parser.add_argument(
        "--prompt-file",
        required=True,
        help="Path to the prompt file (supports wildcards)",
    )
    parser.add_argument(
        "--report-path",
        default="",
        help="Path to the original report file (for metadata, optional)",
    )
    parser.add_argument(
        "--output-dir",
        default="reports/prompts",
        help="Output directory for analysis results (default: reports/prompts)",
    )
    parser.add_argument(
        "--gemini-api-key",
        help="Gemini API key (default: from GEMINI_API_KEY env var)",
    )
    parser.add_argument(
        "--use-cli",
        action="store_true",
        help="Use Gemini CLI via npx instead of API (requires Node.js)",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=300,
        help="Timeout in seconds (default: 300)",
    )
    parser.add_argument(
        "--no-upload",
        action="store_true",
        help="Skip uploading to Google Sheets",
    )

    args = parser.parse_args()

    logger.info("=" * 80)
    logger.info("AI Report Analyzer (Google Gemini Edition)")
    logger.info("=" * 80)
    logger.info("")

    # Find prompt file
    prompt_path = find_latest_file(args.prompt_file)
    logger.info(f"📄 Prompt file: {Path(prompt_path).name}")
    logger.info(f"   Mode: {'Gemini CLI (npx)' if args.use_cli else 'Gemini API'}")
    logger.info("")

    try:
        # Call Gemini CLI or API
        if args.use_cli:
            analysis = call_gemini_cli(prompt_path, timeout=args.timeout)
        else:
            prompt = read_prompt(prompt_path)
            analysis = call_gemini_api(prompt, api_key=args.gemini_api_key, timeout=args.timeout)

        logger.info("")
        logger.info("=" * 80)
        logger.info("📊 ANALYSIS RESULT")
        logger.info("=" * 80)
        logger.info("")
        print(analysis)
        logger.info("")

        # Save analysis
        logger.info("💾 Saving analysis to file...")
        analysis_tool = "Google Gemini CLI (npx)" if args.use_cli else "Google Gemini API"
        output_file = save_analysis(analysis, args.report_path, args.output_dir, analysis_tool)
        logger.info(f"   ✓ Saved to: {output_file}")
        logger.info("")

        # Auto-upload to Google Sheets (unless --no-upload specified)
        upload_to_google_sheets(Path(output_file), skip_upload=args.no_upload)

        # Summary
        logger.info("=" * 80)
        logger.info("✅ ANALYSIS COMPLETE!")
        logger.info("=" * 80)
        logger.info("")
        logger.info(f"📄 Prompt: {Path(prompt_path).name}")
        logger.info(f"💾 Output: {output_file}")
        logger.info("")
        logger.info("=" * 80)

        return 0

    except Exception as e:
        logger.error("")
        logger.error("=" * 80)
        logger.error("❌ ANALYSIS FAILED")
        logger.error("=" * 80)
        logger.error("")
        logger.error(f"Error: {str(e)}")
        logger.error("")
        return 1


if __name__ == "__main__":
    sys.exit(main())
