name: 'Report Statistics and PR Comment'
description: 'Collect report statistics and post PR comment with summary'

inputs:
  reports_dir:
    description: 'Directory containing reports'
    required: false
    default: 'reports'
  google_spreadsheet_id:
    description: 'Google Spreadsheet ID for sharing link'
    required: false
    default: ''
  github_token:
    description: 'GitHub token for PR comments'
    required: true
  email_failed:
    description: 'Whether email notification failed (true/false)'
    required: false
    default: 'false'

outputs:
  json_count:
    description: 'Number of JSON files'
    value: ${{ steps.stats.outputs.json_count }}
  team_comparison_count:
    description: 'Number of team comparison reports'
    value: ${{ steps.stats.outputs.team_comparison_count }}
  member_comparison_count:
    description: 'Number of member comparison reports'
    value: ${{ steps.stats.outputs.member_comparison_count }}
  combined_count:
    description: 'Number of combined reports'
    value: ${{ steps.stats.outputs.combined_count }}
  aggregated_count:
    description: 'Number of aggregated reports'
    value: ${{ steps.stats.outputs.aggregated_count }}
  total_tsv:
    description: 'Total TSV files'
    value: ${{ steps.stats.outputs.total_tsv }}
  prompt_count:
    description: 'Number of analysis prompt files'
    value: ${{ steps.stats.outputs.prompt_count }}
  phase_report_count:
    description: 'Number of detailed phase report files'
    value: ${{ steps.stats.outputs.phase_report_count }}
  total_txt:
    description: 'Total TXT files'
    value: ${{ steps.stats.outputs.total_txt }}

runs:
  using: "composite"
  steps:
    - name: Collect Report Statistics
      id: stats
      shell: bash
      run: |
        REPORTS_DIR="${{ inputs.reports_dir }}"

        # Check if reports directory exists
        if [ ! -d "$REPORTS_DIR" ]; then
          echo "⚠️  Reports directory not found: $REPORTS_DIR"
          echo "json_count=0" >> $GITHUB_OUTPUT
          echo "team_comparison_count=0" >> $GITHUB_OUTPUT
          echo "member_comparison_count=0" >> $GITHUB_OUTPUT
          echo "combined_count=0" >> $GITHUB_OUTPUT
          echo "aggregated_count=0" >> $GITHUB_OUTPUT
          echo "total_tsv=0" >> $GITHUB_OUTPUT
          echo "prompt_count=0" >> $GITHUB_OUTPUT
          echo "phase_report_count=0" >> $GITHUB_OUTPUT
          echo "total_txt=0" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Count different types of files with detailed breakdown

        # JSON files (raw metrics data)
        JSON_COUNT=$(find "$REPORTS_DIR" -name "*.json" -type f 2>/dev/null | wc -l)

        # TSV Reports - Team reports (general)
        TEAM_COMPARISON_COUNT=$(find "$REPORTS_DIR" -name "*comparison_general_*.tsv" -type f 2>/dev/null | wc -l)

        # TSV Reports - Individual member reports (exclude general and combined)
        MEMBER_COMPARISON_COUNT=$(find "$REPORTS_DIR" -name "*comparison_*.tsv" -type f 2>/dev/null | grep -v "general" | wc -l)

        # Combined reports (exclude aggregated)
        COMBINED_COUNT=$(find "$REPORTS_DIR" -name "*combined*report*.tsv" -type f 2>/dev/null | grep -v "aggregated" | wc -l)

        # Aggregated reports (multi-team aggregation)
        AGGREGATED_COUNT=$(find "$REPORTS_DIR" -name "aggregated_*_report_*.tsv" -type f 2>/dev/null | wc -l)

        # Total TSV files
        TOTAL_TSV=$(find "$REPORTS_DIR" -name "*.tsv" -type f 2>/dev/null | wc -l)

        # Analysis prompts
        PROMPT_COUNT=$(find "$REPORTS_DIR" -name "analysis_prompt_*.txt" -type f 2>/dev/null | wc -l)

        # Detailed phase reports (all .txt files excluding analysis prompts)
        PHASE_REPORT_COUNT=$(find "$REPORTS_DIR" -name "*.txt" -type f 2>/dev/null | grep -v "analysis_prompt" | wc -l)

        # Total text files
        TOTAL_TXT=$(find "$REPORTS_DIR" -name "*.txt" -type f 2>/dev/null | wc -l)

        # Export to GitHub output
        echo "json_count=$JSON_COUNT" >> $GITHUB_OUTPUT
        echo "team_comparison_count=$TEAM_COMPARISON_COUNT" >> $GITHUB_OUTPUT
        echo "member_comparison_count=$MEMBER_COMPARISON_COUNT" >> $GITHUB_OUTPUT
        echo "combined_count=$COMBINED_COUNT" >> $GITHUB_OUTPUT
        echo "aggregated_count=$AGGREGATED_COUNT" >> $GITHUB_OUTPUT
        echo "total_tsv=$TOTAL_TSV" >> $GITHUB_OUTPUT
        echo "prompt_count=$PROMPT_COUNT" >> $GITHUB_OUTPUT
        echo "phase_report_count=$PHASE_REPORT_COUNT" >> $GITHUB_OUTPUT
        echo "total_txt=$TOTAL_TXT" >> $GITHUB_OUTPUT

        echo "📊 Report Statistics:"
        echo "  Reports directory: $REPORTS_DIR"
        echo "  Team comparison reports: $TEAM_COMPARISON_COUNT"
        echo "  Member comparison reports: $MEMBER_COMPARISON_COUNT"
        echo "  Combined reports: $COMBINED_COUNT"
        echo "  Aggregated reports: $AGGREGATED_COUNT"
        echo "  Total TSV files: $TOTAL_TSV"
        echo "  Detailed phase reports: $PHASE_REPORT_COUNT"
        echo "  Analysis prompts: $PROMPT_COUNT"
        echo "  Total TXT files: $TOTAL_TXT"

    - name: Comment on PR - Success
      if: (github.event_name == 'pull_request' || github.event_name == 'pull_request_target') && success()
      continue-on-error: true
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const spreadsheetId = '${{ inputs.google_spreadsheet_id }}';
          const sheetsUrl = spreadsheetId
            ? `https://docs.google.com/spreadsheets/d/${spreadsheetId}`
            : null;

          const teamCount = '${{ steps.stats.outputs.team_comparison_count }}' || '0';
          const memberCount = '${{ steps.stats.outputs.member_comparison_count }}' || '0';
          const combinedCount = '${{ steps.stats.outputs.combined_count }}' || '0';
          const aggregatedCount = '${{ steps.stats.outputs.aggregated_count }}' || '0';
          const totalTsv = '${{ steps.stats.outputs.total_tsv }}' || '0';
          const promptCount = '${{ steps.stats.outputs.prompt_count }}' || '0';
          const phaseReportCount = '${{ steps.stats.outputs.phase_report_count }}' || '0';
          const totalTxt = '${{ steps.stats.outputs.total_txt }}' || '0';
          const jsonCount = '${{ steps.stats.outputs.json_count }}' || '0';
          const emailFailed = '${{ inputs.email_failed }}' === 'true';

          const artifactsUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

          // Calculate total reports and breakdown
          const totalReports = parseInt(totalTsv) + parseInt(totalTxt);

          // Check if no reports were generated (skipped execution)
          if (totalReports === 0) {
            const body = '## ℹ️ Report Generation Skipped\n\n' +
              '**Reason**: Only test configs or CI workflow files were modified.\n\n' +
              '---\n\n' +
              '💡 **Note**: Report generation only runs when production config files are changed:\n' +
              '- Production configs: `config/<team>/jira_report_config.yaml` or `config/<team>/pr_report_config.yaml`\n' +
              '- Test configs (skipped): `config/test-*/...`\n\n' +
              '✅ This PR can be merged if all tests pass.';

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
            return;
          }

          // Calculate individual members count (total - team reports - combined reports)
          const individualMembersCount = parseInt(memberCount) / 2; // Divide by 2 (Jira + PR)

          let body = '## ✅ Reports Generated Successfully\n\n';

          // File statistics - detailed breakdown (Option 2 format)
          body += '📊 **Report Summary**:\n';
          body += `- **Total Reports**: ${totalReports} files (${totalTsv} TSV + ${totalTxt} TXT)\n`;
          body += `  - Team comparison: ${teamCount} TSV (Jira team + PR team)\n`;
          body += `  - Individual comparison: ${memberCount} TSV (${individualMembersCount} Jira members + ${individualMembersCount} PR members)\n`;
          body += `  - Combined views: ${combinedCount} TSV (Jira combined + PR combined)\n`;
          if (parseInt(aggregatedCount) > 0) {
            body += `  - **Aggregated views** 🔗: ${aggregatedCount} TSV (Multi-team aggregation)\n`;
          }
          if (parseInt(phaseReportCount) > 0) {
            body += `  - Detailed phase reports: ${phaseReportCount} TXT (per-phase breakdowns for all members)\n`;
          }
          if (parseInt(promptCount) > 0) {
            body += `- **AI Analysis Prompts**: ${promptCount} files (Jira prompt + PR prompt)\n`;
          }
          if (parseInt(jsonCount) > 0) {
            body += `- **Raw Metrics Data**: ${jsonCount} JSON files (raw API responses)\n`;
          }
          body += '\n';

          // Email notification status (optional feature)
          if (emailFailed) {
            body += '📧 **Email Notifications** (Optional): ⚠️ Failed to send (check SMTP configuration in repository secrets)\n\n';
          } else {
            body += '📧 **Email Notifications** (Optional): ✅ Sent to team members\n';
            body += '- Each member received their **personal anonymous identifier** (e.g., Developer-A3F2)\n';
            body += '- Use this ID to find your personal metrics in the reports generated by this PR\n';
            body += '- You can optionally share your ID with your manager if you choose\n';
            body += '- *Note: Email notifications are optional and can be disabled in config*\n\n';
          }

          // Links
          body += '📥 **Access Reports**: ';
          if (sheetsUrl) {
            body += `[View in Google Sheets](${sheetsUrl}) | `;
          }
          body += `[Download All Files](${artifactsUrl})\n\n`;

          // Aggregation info
          if (parseInt(aggregatedCount) > 0) {
            body += '> 🔗 **Multi-Team Aggregation**: This workflow aggregated reports from multiple sub-teams into unified views. ';
            body += 'Aggregated reports combine metrics across all configured teams for organization-level insights.\n\n';
          }

          // AI Analysis tip
          if (parseInt(promptCount) > 0) {
            const repoUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}`;
            body += '> 💡 **AI Analysis Options**:\n';
            body += '> - **Quick & Manual**: Download prompt files from artifacts → paste into Claude/ChatGPT/Gemini\n';
            body += `> - **Automated & Local**: Use Claude CLI or API to generate reports from combined TSV files → See [AI-Powered Analysis](${repoUrl}/blob/master/README.md#ai-powered-analysis-experimental)\n\n`;
          }

          body += '---\n\n';
          body += '⚠️ **Important**: ❌ DO NOT MERGE - 🔒 Manually close this PR after reviewing reports\n';

          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
